version: "3.8"

services:
  app:
    image: ghcr.io/mahn-ke/backup-trigger:latest@sha256:a52a515aaae9f9601ac3dff60d3161bc69e9337ceab711c74402fb2844462f79
    restart: unless-stopped
    environment:
      TF_VAR_GITHUB_PAT: ${TF_VAR_GITHUB_PAT}
      RUN_AT_STARTUP: false
